from pathlib import Path

import pytest

from masterblaster_control import utils


def test_report_prefix_rejects_path_traversal(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    with pytest.raises(ValueError):
        utils.write_watermarked_report("draft", prefix="../escape")

    with pytest.raises(ValueError):
        utils.write_watermarked_report("draft", prefix="/absolute")


def test_report_writer_uses_reports_directory_for_safe_prefix(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

    path = Path(utils.write_watermarked_report("draft", prefix="report_draft"))

    assert path.parent == Path("reports")
    assert path.name.startswith("report_draft_")
    content = path.read_text(encoding="utf-8")
    assert content.startswith("# CONFIDENTIAL") or content.startswith("# Generated by")
