from __future__ import annotations

import os
from datetime import datetime


def dark_kali_stylesheet():
    return """
    QMainWindow, QWidget { background-color: #1a1a1a; color: #cccccc; }
    QTabWidget::pane { border: 1px solid #333; }
    QTabBar::tab { background: #222; padding: 8px 16px; }
    QTabBar::tab:selected { background: #2a2a2a; border-bottom: 2px solid #00ff9d; }
    QPushButton { background: #2d2d2d; border: 1px solid #444; padding: 6px 12px; }
    QPushButton:hover { background: #3a3a3a; }
    QLineEdit, QTextEdit, QPlainTextEdit { background: #111; border: 1px solid #333; font-family: Consolas, monospace; }
    QListWidget { background: #111; border: 1px solid #333; }
    QProgressBar { background: #222; border: 1px solid #444; text-align: center; }
    QProgressBar::chunk { background: #00ff9d; }
    QLabel { color: #aaa; }
    """


def ensure_dirs():
    os.makedirs("reports", exist_ok=True)
    os.makedirs("logs", exist_ok=True)


def write_watermarked_report(content, watermark=True, prefix="report"):
    ensure_dirs()
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = f"reports/{prefix}_{ts}.md"
    with open(path, "w", encoding="utf-8") as report_file:
        if watermark:
            report_file.write("# Generated by MasterBlaster P0 Authorized Assessment Simulator\n")
            report_file.write("# Simulator evidence draft only. No compliance or certification claim.\n\n")
        report_file.write(content)
    return path


def write_export_file(content: str, prefix: str, extension: str) -> str:
    ensure_dirs()
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = f"reports/{prefix}_{ts}.{extension}"
    with open(path, "w", encoding="utf-8") as export_file:
        export_file.write(content)
    return path
