from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

SAFE_REPORT_PREFIX_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")


def warlord_whip_button_style() -> str:
    return (
        "QPushButton {"
        " background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ff2222, stop:1 #8b0000);"
        " color: #ffd700; font-weight: bold; font-size: 14px;"
        " border: 2px solid #ff4444; border-radius: 6px; padding: 10px 24px;"
        "}"
        "QPushButton:hover { background: #cc0000; }"
        "QPushButton:pressed { background: #5a0000; }"
        "QPushButton:disabled { background: #333; color: #666; border-color: #444; }"
    )


def annihilation_toggle_style() -> str:
    return "QCheckBox { color: #ff6666; font-weight: bold; } QCheckBox::indicator:checked { background: #8b0000; }"


def dark_kali_stylesheet():
    return """
    QMainWindow, QWidget { background-color: #1a1a1a; color: #cccccc; }
    QTabWidget::pane { border: 1px solid #333; }
    QTabBar::tab { background: #222; padding: 8px 16px; }
    QTabBar::tab:selected { background: #2a2a2a; border-bottom: 2px solid #00ff9d; }
    QPushButton { background: #2d2d2d; border: 1px solid #444; padding: 6px 12px; }
    QPushButton:hover { background: #3a3a3a; }
    QLineEdit, QTextEdit, QPlainTextEdit { background: #111; border: 1px solid #333; font-family: Consolas, monospace; }
    QListWidget { background: #111; border: 1px solid #333; }
    QProgressBar { background: #222; border: 1px solid #444; text-align: center; }
    QProgressBar::chunk { background: #00ff9d; }
    QLabel { color: #aaa; }
    """


def ensure_dirs():
    Path("reports").mkdir(exist_ok=True)
    Path("logs").mkdir(exist_ok=True)


def write_watermarked_report(content, watermark=True, prefix="report"):
    if not SAFE_REPORT_PREFIX_RE.fullmatch(prefix):
        raise ValueError("report prefix must be a safe lowercase slug")
    ensure_dirs()
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = Path("reports") / f"{prefix}_{ts}.md"
    with path.open("w", encoding="utf-8") as report_file:
        if watermark:
            report_file.write("# Generated by MasterBlaster P0 Authorized Assessment Simulator\n")
            report_file.write("# Simulator evidence draft only. No compliance or certification claim.\n\n")
        report_file.write(content)
    return str(path)


def write_export_file(content: str, prefix: str, extension: str) -> str:
    if not SAFE_REPORT_PREFIX_RE.fullmatch(prefix):
        raise ValueError("export prefix must be a safe lowercase slug")
    ensure_dirs()
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = Path("reports") / f"{prefix}_{ts}.{extension}"
    path.write_text(content, encoding="utf-8")
    return str(path)